// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PictureCallCommon","status":true,"description":"Clickable picture plugin","parameters":{"TransparentConsideration":"ON","GameVariablePictureNum":"0","GameVariableTouchX":"","GameVariableTouchY":"","SuppressTouch":"OFF"}},
{"name":"Yami_SkipTitle","status":true,"description":"テストプレイ用にタイトルシーンを飛ばすことができます。","parameters":{}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.1) 指定された番号のスイッチがONの間、\nプレイヤー操作によるキャラの移動を禁止します。","parameters":{"Default_Move_Flag":"1"}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}}
];
